version: '3'

services:
  postgres:
    image: 'postgres:alpine'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=link_shortener'
    ports:
      - "5432:5432"

  backend:
    build: ./
    container_name: 'java-app'
    ports:
      - "8080:8080"
    environment:
      - 'PGPASSWORD=password'
      - 'DATASOURCE_URL=jdbc:postgresql://postgres:5432/link_shortener'
    depends_on:
      - postgres
